defaults:
  - base_options
  - dataset: cifar10
  - model: dtp
  - network: simple_vgg
  - trainer: default.yaml
  - callbacks: default.yaml
  - optional model_network: ${model}_${network}
  - optional model_network_dataset: ${model}_${network}_${dataset}
  - logger: null # use logger=wandb to enable wandb logging.
  - _self_
  - override hydra/sweeper: orion
